# Generated by Django 3.0.8 on 2020-08-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_items_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
