# Generated by Django 3.0.8 on 2020-08-16 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200816_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Items'),
        ),
    ]
