# Generated by Django 3.0.8 on 2020-08-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200816_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='posted_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
