# Generated by Django 3.0.8 on 2020-08-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200816_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
